feign:
  httpclient:
    connection-timeout: 3000
    ok-http:
      read-timeout: 5000

spring:
  elasticsearch:
    uris: http://localhost:9200

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    listener:
      simple:
        prefetch: 1
        concurrency: 3
        acknowledge-mode: manual